application_path: "/edx/app/edxapp"
edxapp_subapps:
  - cms
  - lms
play_name: "edxapp"
db_migration_user: "www-data"

# Migration table/duration alerting on stage.
databases:
  default:
    migration_duration_threshold: 10
    tables_to_alert:
      - courseware_studentmodule
      - student_courseenrollment
  student_module_history:
    migration_duration_threshold: 10
    tables_to_alert:
      - coursewarehistoryextended_studentmodulehistoryextended
alert_from_address: migration.alert@tools.edx.org
alert_to_addresses:
  - bbeggs@edx.org
  - jeskew@edx.org
  - feanil@edx.org
  - cale@edx.org

# Branch merging and cleanup post-deploy.
github_org: edx
github_repo: edx-platform
rc_branch: release-candidate
release_branch: release
release_to_master_branch: release-mergeback-to-master
master_branch: master

# For edx-platform tests, wait 35 minutes before polling. Then poll every 20 seconds for 15 minutes.
initial_poll_wait: 2100
max_poll_tries: 45
poll_interval: 20
