materials:
  - url: "https://github.com/edx/tubular"
    branch: "master"
    material_name: "tubular"
    polling: "True"
    destination_directory: "tubular"
    ignore_patterns:
      - '**/*'
  - url: &configuration_url "https://github.com/edx/configuration"
    branch: "master"
    material_name: "configuration"
    polling: "True"
    destination_directory: "configuration"
    ignore_patterns:
      - '**/*'
  - url: &app_repo "https://github.com/edx/edx-platform"
    branch: "release-candidate"
    material_name: "edx-platform"
    polling: "True"
    destination_directory: "edx-platform"
    ignore_patterns:
      - '**/*'
  - url: &edx_configuration_secure_repo "git@github.com:edx-ops/edx-secure.git"
    branch: "master"
    material_name: "edx-secure"
    polling: "True"
    destination_directory: "edx-secure"
    ignore_patterns:
      - '**/*'
  - url: &edge_configuration_secure_repo "git@github.com:edx-ops/edge-secure.git"
    branch: "master"
    material_name: "edge-secure"
    polling: "True"
    destination_directory: "edge-secure"
    ignore_patterns:
      - '**/*'
  - url: &mckinsey_configuration_secure_repo "git@github.com:edx-ops/mckinsey-secure.git"
    branch: "master"
    material_name: "mckinsey-secure"
    polling: "True"
    destination_directory: "mckinsey-secure"
    ignore_patterns:
      - '**/*'
  - url: &theme_url "git@github.com:edx/edx-microsite.git"
    branch: "master"
    material_name: "edx-microsite"
    polling: "True"
    destination_directory: "edx-microsite"
    ignore_patterns:
      - '**/*'
  - url: &edx_configuration_internal_repo "git@github.com:edx/edx-internal.git"
    branch: "master"
    material_name: "edx-internal"
    polling: "True"
    destination_directory: "edx-internal"
    ignore_patterns:
      - '**/*'
  - url: &edge_configuration_internal_repo "git@github.com:edx/edge-internal.git"
    branch: "master"
    material_name: "edge-internal"
    polling: "True"
    destination_directory: "edge-internal"
    ignore_patterns:
      - '**/*'
  - url: &mckinsey_configuration_internal_repo "git@github.com:mckinseyacademy/mckinsey-internal.git"
    branch: "master"
    material_name: "mckinsey-internal"
    polling: "True"
    destination_directory: "mckinsey-internal"
    ignore_patterns:
      - '**/*'

configuration_url: *configuration_url
app_repo: *app_repo
theme_url: *theme_url
edx_configuration_secure_repo: *edx_configuration_secure_repo
edge_configuration_secure_repo: *edge_configuration_secure_repo
mckinsey_configuration_secure_repo: *mckinsey_configuration_secure_repo
edx_configuration_internal_repo: *edx_configuration_internal_repo
edge_configuration_internal_repo: *edge_configuration_internal_repo
mckinsey_configuration_internal_repo: *mckinsey_configuration_internal_repo
